"""仮説キャプチャの賭け化：確認の目印(checkpoint)＋向きから主張を自動生成する。

なぜこの機能があるか（→ docs/thesis_capture_redesign.md）:
実ユーザー検証で「検証(答え合わせ)が回らない」原因が④数値への接続だと判明。
記録ツールの④は"数字のモデル化"ではなく「答え合わせで見る目印を1つ先にコミット」。
目印＋向きから主張(claim)を自動生成することで「一文でまとまらない」を解消し、
検証時に「決めた目印は実際どうだったか」を機械的に問い返せるようにする。
"""
import pytest
from django.urls import reverse

from stockdiary.models import Thesis


class TestComposeClaim:
    """目印＋向き → 主張文の自動組み立て（純関数・DB不要）。"""

    def test_up_direction(self):
        assert Thesis.compose_claim('次決算の資金利益', 'up') == '次決算の資金利益が上がる'

    def test_event_direction(self):
        assert Thesis.compose_claim('TOBの成立', 'happened') == 'TOBの成立が実現する'

    def test_no_direction_returns_checkpoint(self):
        # 向きが無ければ目印そのものを主張にする（定性チェック等）
        assert Thesis.compose_claim('新製品の評判', '') == '新製品の評判'

    def test_empty_checkpoint_returns_empty(self):
        assert Thesis.compose_claim('', 'up') == ''
        assert Thesis.compose_claim('   ', 'up') == ''


@pytest.mark.django_db
class TestThesisCheckpoint:
    def test_horizon_defaults_to_next_earnings(self, sample_diary):
        """既定の検証期間は「次の決算まで」＝答え合わせが年数回来るようにする。"""
        t = Thesis.objects.create(diary=sample_diary, claim='x')
        assert t.horizon == 'next_earnings'

    def test_claim_autogenerated_from_checkpoint(self, authenticated_client, sample_diary):
        """claim 空欄でも、目印＋向きから主張が自動生成されて保存される。"""
        url = reverse('stockdiary:thesis_create', kwargs={'diary_id': sample_diary.pk})
        resp = authenticated_client.post(url, {
            'claim': '',
            'checkpoint': '次決算の営業利益',
            'checkpoint_direction': 'up',
            'horizon': 'next_earnings',
        }, HTTP_HX_REQUEST='true')
        assert resp.status_code == 200
        t = Thesis.objects.filter(diary=sample_diary).order_by('-id').first()
        assert t is not None
        assert t.claim == '次決算の営業利益が上がる'
        assert t.checkpoint == '次決算の営業利益'
        assert t.checkpoint_direction == 'up'

    def test_freeform_claim_preserved_without_checkpoint(self, authenticated_client, sample_diary):
        """自由記述の逃げ道：claim を直接書けば目印なしでも保存される（幅を殺さない）。"""
        url = reverse('stockdiary:thesis_create', kwargs={'diary_id': sample_diary.pk})
        resp = authenticated_client.post(url, {
            'claim': 'この経営者の資本配分を長期で信じる',
            'checkpoint': '',
            'checkpoint_direction': '',
            'horizon': 'long',
        }, HTTP_HX_REQUEST='true')
        assert resp.status_code == 200
        t = Thesis.objects.filter(diary=sample_diary).order_by('-id').first()
        assert t is not None
        assert t.claim == 'この経営者の資本配分を長期で信じる'
        assert t.checkpoint == ''

    def test_both_blank_is_rejected(self, authenticated_client, sample_diary):
        """主張も目印も無ければ保存しない（少なくとも一方が必要）。"""
        url = reverse('stockdiary:thesis_create', kwargs={'diary_id': sample_diary.pk})
        before = Thesis.objects.filter(diary=sample_diary).count()
        resp = authenticated_client.post(url, {
            'claim': '',
            'checkpoint': '',
            'checkpoint_direction': '',
            'horizon': 'next_earnings',
        }, HTTP_HX_REQUEST='true')
        # HTMX 無効時はフォームを再描画（200）し、Thesis は増えない
        assert Thesis.objects.filter(diary=sample_diary).count() == before

    def test_karte_shows_checkpoint(self, authenticated_client, sample_diary):
        """カルテに目印が表示される。"""
        Thesis.objects.create(diary=sample_diary, claim='営業利益が上がる',
                              checkpoint='次決算の営業利益', checkpoint_direction='up')
        resp = authenticated_client.get(reverse('stockdiary:detail', kwargs={'pk': sample_diary.pk}))
        html = resp.content.decode()
        assert 'karte-checkpoint' in html
        assert '次決算の営業利益' in html
