# Generated by Django 5.2.3 on 2026-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_analysis', '0004_earningsschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsschedule',
            name='is_estimated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='予想日フラグ'),
        ),
    ]
