# Generated by Django 5.2.3 on 2026-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings_analysis", "0005_earningsschedule_is_estimated"),
    ]

    operations = [
        migrations.AddField(
            model_name="earningsschedule",
            name="confidence",
            field=models.CharField(blank=True, max_length=10, verbose_name="予測精度"),
        ),
        migrations.AddField(
            model_name="earningsschedule",
            name="prediction_window_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="予測誤差(日)"
            ),
        ),
    ]
