# Generated by Django 5.2.3 on 2026-07-12
from django.db import migrations, models


class Migration(migrations.Migration):
    """信用ショート（新規売り→返済買い）を専用フィールドで別建て集計するための追加。

    Transaction.margin_action（新規/返済）が無いと、同一銘柄でロングと
    ショートを同時に保有した場合に集計が破綻する（詳細は
    aggregate_service.py の _recalculate_all のdocstring）。
    """

    dependencies = [
        ("stockdiary", "0021_thesis_checkpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="margin_action",
            field=models.CharField(
                blank=True,
                choices=[("open", "新規"), ("close", "返済")],
                max_length=10,
                null=True,
                verbose_name="信用建玉区分",
            ),
        ),
        migrations.AddField(
            model_name="stockdiary",
            name="margin_short_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="信用売り建玉数",
            ),
        ),
        migrations.AddField(
            model_name="stockdiary",
            name="margin_short_average_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="信用売り平均建単価",
            ),
        ),
        migrations.AddField(
            model_name="stockdiary",
            name="margin_short_total_proceeds",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="信用売り建玉総代金",
            ),
        ),
        migrations.AddField(
            model_name="stockdiary",
            name="margin_short_realized_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="信用売り実現損益",
            ),
        ),
    ]
